from sqlalchemy import Column, Integer, String, ForeignKey, DateTime, Text
from sqlalchemy.orm import relationship
from backend.app.core.config import Base
from datetime import datetime, timezone

class PatientIgnoredAutoGeneratedItem(Base):
    __tablename__ = "patient_ignored_auto_generated_items"
    
    id = Column(Integer, primary_key=True, index=True)
    patient_id = Column(Integer, ForeignKey("patients.patient_id"), nullable=False)
    doctor_id = Column(Integer, ForeignKey("doctors.id"), nullable=False)
    entity_type = Column(String(50), nullable=False)  # 'follow_up_action', 'recommendation', 'referral', 'lifestyle_advice', 'presumptive_diagnosis', 'test_to_order'
    catalog_item_key = Column(Text, nullable=False)  # JSON string or text to identify the specific catalog item
    ignored_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    
    # Relationships
    patient = relationship("Patient", back_populates="ignored_auto_generated_items")
    doctor = relationship("Doctor", back_populates="ignored_auto_generated_items")
