from pydantic import BaseModel
from typing import Optional
from datetime import datetime

class PatientIgnoredAutoGeneratedItemBase(BaseModel):
    patient_id: int
    doctor_id: int
    entity_type: str
    catalog_item_key: str

class PatientIgnoredAutoGeneratedItemCreate(PatientIgnoredAutoGeneratedItemBase):
    pass

class PatientIgnoredAutoGeneratedItemResponse(PatientIgnoredAutoGeneratedItemBase):
    id: int
    ignored_at: datetime
    
    class Config:
        from_attributes = True
