'use client';

import React from 'react';
import { Badge } from '@/components/ui/badge';
import { Sparkles } from 'lucide-react';

interface AutoGeneratedLabelProps {
  className?: string;
  size?: 'sm' | 'md' | 'lg';
}

export const AutoGeneratedLabel: React.FC<AutoGeneratedLabelProps> = ({ 
  className = '', 
  size = 'sm' 
}) => {
  const sizeClasses = {
    sm: 'text-xs px-2 py-0.5',
    md: 'text-sm px-2.5 py-1',
    lg: 'text-base px-3 py-1.5'
  };

  const iconSizes = {
    sm: 'w-3 h-3',
    md: 'w-4 h-4', 
    lg: 'w-5 h-5'
  };

  return (
    <Badge
      variant="secondary"
      className={`
        bg-emerald-50 text-emerald-700 border-emerald-200 
        hover:bg-emerald-100 transition-colors duration-200
        font-medium rounded-full flex items-center gap-1
        shadow-sm ring-1 ring-emerald-200/50
        ${sizeClasses[size]} ${className}
      `}
    >
      <Sparkles className={`${iconSizes[size]} fill-current`} />
      <span>Auto-generated</span>
    </Badge>
  );
};

export default AutoGeneratedLabel;
